dist: trusty

language: java

jdk:
  - oraclejdk13

services:
  - postgresql

addons:
  postgresql: "9.5"

install: true

before_install:
  - psql -c 'create database "bethehero";' -U postgres

script:
  - chmod +x ./.ci/script.sh 
  - ./.ci/script.sh
  
env:
 global:
   - CODECOV_TOKEN="92ab5c75-9ee3-4ed2-ba5a-e3438ab9ee4a"
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
