codecov:
  token: "92ab5c75-9ee3-4ed2-ba5a-e3438ab9ee4a"
  
  ignore:
  - "src/main/java/br/br/com/thehero/config/*"
  - "src/main/java/br/br/com/thehero/domain/*"
  - "src/main/java/br/br/com/thehero/dto/*"
  - "src/main/java/br/br/com/thehero/exception/*"
  - "src/main/java/br/br/com/thehero/login/config/*"
  - "src/main/java/br/br/com/thehero/login/model/*"
  - "src/main/java/br/br/com/thehero/login/repository/*"
  - "src/main/java/br/br/com/thehero/login/request/*"
  - "src/main/java/br/br/com/thehero/login/response/*"
  - "src/main/java/br/br/com/thehero/logout/request/*"